# Generated by Django 2.1.7 on 2024-04-03 03:24

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0006_auto_20240403_0011'),
    ]

    operations = [
        migrations.AlterField(
            model_name='todo',
            name='created_at',
            field=models.DateField(blank=True, default=datetime.datetime(2024, 4, 3, 0, 24, 7, 154494)),
        ),
    ]
